name: getx_base_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  email_validator: ^3.0.0
  carousel_slider: ^5.0.0
  rxcache_network_image: ^1.0.7
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get_it: ^7.7.0
  getwidget: ^4.0.0
  go_router: ^14.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  permission_handler: ^11.3.1
  phone_numbers_parser: ^8.3.0
  readmore: ^3.0.0
  share_plus: ^10.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  get: ^4.6.6
  path_provider: ^2.1.4
  flutter_dropdown_alert: ^1.0.7
  build_context_provider: ^1.1.0
  geolocator: ^11.0.0
  playx_version_update: ^0.0.7
  version: ^3.0.2
  flutter_widget_from_html: ^0.15.3
  pretty_dio_logger: ^1.4.0
  dio: ^5.5.0+1
  dartz: ^0.10.1
  logger: ^2.4.0
  freezed: ^2.4.7
  flutter_spinkit: ^5.2.1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  # fast_cached_network_image: ^1.3.0+2
  provider: ^6.1.2
  redacted: ^1.0.12
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  device_info_plus: ^10.1.2


dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.5.0+1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  package_rename_plus: ^1.0.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.


dependency_overrides:
  intl: 0.19.0


flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400

  generate: true
  uses-material-design: true

  assets:
    - keys.env
    - assets/
    - assets/icons/
